/* Infografía interactiva · JavaScript puro: progreso, navegación activa, reveal, feedback y accesibilidad. */
(()=>{'use strict';
const prm=matchMedia('(prefers-reduced-motion: reduce)').matches,$=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const state={member:'madre',layer:'necesidad',tool:'genograma',mode:'case',route:0,checked:new Set()};
const members=[['madre','Madre','Sobrecarga de cuidado, posible ansiedad y artrosis. Requiere lectura de autonomía funcional, descanso, red de apoyo y coordinación sanitaria-social.'],['hijo','Hijo','Consumo problemático de opioides/cannabis y fragilidad de adherencia. La mirada socioeducativa prioriza reducción de daños, vínculo, motivación y recursos comunitarios.'],['padre','Padre','Consumo de alcohol y participación ambivalente en la dinámica familiar. Conviene valorar límites, corresponsabilidad, apoyo familiar y derivación especializada si procede.'],['sistema','Sistema familiar','La unidad de intervención no es una persona aislada, sino una red de vínculos, sobrecargas, silencios, apoyos informales y oportunidades preventivas.']];
const layers=[['salud','Dato sanitario','El dato sanitario ordena el lenguaje profesional, pero no debe convertirse en diagnóstico emitido desde la intervención socioeducativa.'],['necesidad','Necesidad social','La necesidad social traduce el problema en autonomía, ingresos, adherencia, convivencia, cuidado, participación y acceso efectivo a apoyos.'],['riesgo','Riesgo/protección','El análisis debe equilibrar factores de riesgo con factores de protección: vínculos, motivación, recursos, escuela/comunidad y capacidad de cuidado.'],['apoyo','Apoyo evaluable','La intervención se concreta en objetivos breves, responsables definidos, coordinación, seguimiento e indicadores observables de mejora.']];
const tools=[{id:'genograma',name:'Genograma profesional',sub:'Composición, convivencia y vínculos.',desc:'Representa estructura familiar, relaciones y concentración de problemas de salud o cuidado.',case:['Diferencia miembros, convivencia y cargas de cuidado.','Permite detectar alianzas, aislamiento y repetición de patrones.'],proposal:['Actualizarlo en entrevistas sucesivas.','Usarlo para acordar apoyos y límites familiares sin culpabilizar.']},{id:'ecomapa',name:'Ecomapa',sub:'Red formal e informal.',desc:'Visualiza recursos sanitarios, sociales, educativos, comunitarios y vínculos de tensión o apoyo.',case:['Localiza apoyos disponibles y ausentes.','Muestra dependencia excesiva de una sola cuidadora.'],proposal:['Activar recursos comunitarios de baja barrera.','Coordinar servicios evitando duplicidades.']},{id:'trayectoria',name:'Trayectoria vital',sub:'Secuencia de eventos y crisis.',desc:'Ordena antecedentes, puntos de inflexión, recaídas, sobrecargas y oportunidades preventivas.',case:['Evita interpretar la crisis como hecho aislado.','Ayuda a situar consumo, salud mental y dependencia en una historia.'],proposal:['Detectar momentos críticos y señales de alerta.','Revisar objetivos por fases temporales.']},{id:'matriz',name:'Matriz funcional',sub:'Necesidades, riesgos y apoyos.',desc:'Cruza necesidades con capacidades, barreras, recursos y prioridad de intervención.',case:['Distingue urgencia, importancia y viabilidad.','Reduce la dispersión del plan de caso.'],proposal:['Priorizar pocos objetivos verificables.','Asignar responsable, plazo e indicador por cada apoyo.']},{id:'plan',name:'Plan socioeducativo',sub:'Acción coordinada y seguimiento.',desc:'Convierte la lectura del caso en acciones, coordinación, prevención y evaluación.',case:['Integra salud, autonomía, familia y comunidad.','Hace visible qué se hará, quién lo hará y cuándo se revisará.'],proposal:['Formular objetivos SMART adaptados al caso.','Registrar avances y ajustar la intervención con evidencias.']}];
const route=[['Problema de salud','Dato inicial','Se identifican consumo, ansiedad, dolor, dependencia o pérdida de autonomía como datos relevantes, no como explicación total de la persona.'],['CIE-11 orientativa','Lenguaje común','La clasificación ayuda a nombrar fenómenos sanitarios, siempre con prudencia y sin invadir la competencia diagnóstica clínica.'],['Cautela ética','No reducir','La etiqueta no sustituye historia de vida, contexto, derechos, deseos, barreras ni factores de protección.'],['Necesidad social','Traducción','El dato se traduce en necesidades de adherencia, apoyo familiar, autonomía, ingresos, vivienda, red comunitaria y participación.'],['Apoyo socioeducativo','Acción','La intervención formula acompañamiento, coordinación, derivación, reducción de daños, educación familiar y seguimiento evaluable.']];
const checks=['Distingue dato sanitario, hipótesis social y diagnóstico clínico.','Incluye factores de riesgo y protección.','Formula apoyos concretos, realistas y evaluables.','Prevé coordinación sociosanitaria y comunitaria.','Respeta autonomía, confidencialidad y no estigmatización.'];
function toast(m){const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
function progress(){const b=$('#progress-bar');if(!b)return;const max=document.documentElement.scrollHeight-innerHeight;b.style.width=(max<=0?0:Math.min(100,Math.max(0,scrollY/max*100)))+'%'}
function reading(){const o=$('#reading-estimate');if(!o)return;const n=(document.body.innerText||'').trim().split(/\s+/).filter(Boolean).length;o.textContent='Lectura estimada: '+Math.max(3,Math.ceil(n/220))+' minutos.'}
function menu(){const tg=$('#menu-toggle'),m=$('#menu');if(!tg||!m)return;tg.addEventListener('click',()=>{const open=tg.getAttribute('aria-expanded')!=='true';tg.setAttribute('aria-expanded',open);m.classList.toggle('open',open);document.body.classList.toggle('menu-open',open)});$$('a',m).forEach(a=>a.addEventListener('click',()=>{tg.setAttribute('aria-expanded','false');m.classList.remove('open');document.body.classList.remove('menu-open')}))}
function reveal(){const items=$$('.reveal');if(prm||!('IntersectionObserver'in window)){items.forEach(i=>i.classList.add('visible'));return}const ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');ob.unobserve(e.target)}}),{threshold:.14});items.forEach(i=>ob.observe(i))}
function spy(){const links=$$('[data-nav-link]'),secs=links.map(a=>$(a.getAttribute('href'))).filter(Boolean);if(!links.length||!('IntersectionObserver'in window))return;const ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-35% 0px -55% 0px',threshold:.01});secs.forEach(s=>ob.observe(s))}
function pressed(btns,id){btns.forEach(b=>{const a=b.dataset.id===id;b.classList.toggle('active',a);b.setAttribute('aria-pressed',a)})}
function caseExplorer(){const mb=$('#member-buttons'),lb=$('#layer-buttons'),out=$('#case-output'),fb=$('#case-feedback');if(!mb||!lb||!out||!fb)return;mb.innerHTML=members.map(m=>`<button class="choice" type="button" data-id="${m[0]}" aria-pressed="false">${m[1]}</button>`).join('');lb.innerHTML=layers.map(l=>`<button class="choice" type="button" data-id="${l[0]}" aria-pressed="false">${l[1]}</button>`).join('');const render=()=>{const m=members.find(x=>x[0]===state.member),l=layers.find(x=>x[0]===state.layer);pressed($$('button',mb),state.member);pressed($$('button',lb),state.layer);out.textContent=`${m[1]}: ${m[2]} ${l[1]}: ${l[2]}`;fb.textContent=`Lectura activa: ${m[1].toLowerCase()} + ${l[1].toLowerCase()}.`};mb.addEventListener('click',e=>{const b=e.target.closest('button[data-id]');if(!b)return;state.member=b.dataset.id;render();toast('Foco de observación actualizado.')});lb.addEventListener('click',e=>{const b=e.target.closest('button[data-id]');if(!b)return;state.layer=b.dataset.id;render();toast('Capa profesional actualizada.')});render()}
function toolLab(){const list=$('#tool-list'),title=$('#tool-title'),desc=$('#tool-description'),detail=$('#tool-detail'),modes=$$('[data-mode]');if(!list||!title||!desc||!detail)return;list.innerHTML=tools.map(t=>`<button class="tool-card" type="button" data-id="${t.id}" aria-pressed="false"><strong>${t.name}</strong><small>${t.sub}</small></button>`).join('');const render=()=>{const t=tools.find(x=>x.id===state.tool)||tools[0];pressed($$('button',list),state.tool);modes.forEach(b=>{const a=b.dataset.mode===state.mode;b.classList.toggle('active',a);b.setAttribute('aria-pressed',a)});title.textContent=t.name;desc.textContent=t.desc;detail.innerHTML='<ul>'+t[state.mode].map(i=>`<li>${i}</li>`).join('')+'</ul>'};list.addEventListener('click',e=>{const b=e.target.closest('button[data-id]');if(!b)return;state.tool=b.dataset.id;render();toast('Herramienta seleccionada.')});modes.forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;render();detail.focus({preventScroll:true})}));render()}
function routeLab(){const list=$('#route-steps'),lab=$('#route-label'),title=$('#route-title'),txt=$('#route-text'),fb=$('#route-feedback');if(!list||!lab||!title||!txt||!fb)return;list.innerHTML=route.map((r,i)=>`<li><button class="route-step" type="button" data-index="${i}" aria-pressed="false"><span><strong>${r[0]}</strong><span>${r[1]}</span></span></button></li>`).join('');const render=()=>{const r=route[state.route];$$('button',list).forEach((b,i)=>{const a=i===state.route;b.classList.toggle('active',a);b.setAttribute('aria-pressed',a)});lab.textContent=`Paso ${state.route+1} de ${route.length}`;title.textContent=r[0];txt.textContent=r[2];fb.textContent=state.route===route.length-1?'Ruta completada: la etiqueta se ha convertido en apoyo coordinado y evaluable.':'Continúa la ruta para completar la traducción socioeducativa.'};list.addEventListener('click',e=>{const b=e.target.closest('button[data-index]');if(!b)return;state.route=Number(b.dataset.index);render();toast(`Paso ${state.route+1} activado.`)});render()}
function checklist(){const list=$('#checklist'),fb=$('#checklist-feedback');if(!list||!fb)return;list.innerHTML=checks.map((c,i)=>`<li><button type="button" data-index="${i}" aria-pressed="false"><span class="checkmark" aria-hidden="true">+</span><span>${c}</span></button></li>`).join('');const render=()=>{$$('button',list).forEach(b=>{const i=Number(b.dataset.index),a=state.checked.has(i);b.setAttribute('aria-pressed',a);$('.checkmark',b).textContent=a?'✓':'+'});const n=state.checked.size,t=checks.length;fb.textContent=n===t?`Checklist completo: ${n}/${t}. La lectura mantiene trazabilidad y cierre preventivo.`:`Progreso de calidad: ${n}/${t} criterios marcados.`};list.addEventListener('click',e=>{const b=e.target.closest('button[data-index]');if(!b)return;const i=Number(b.dataset.index);state.checked.has(i)?state.checked.delete(i):state.checked.add(i);render()});render()}
function utils(){const fs=$('#fullscreen-button'),pr=$('#print-button'),copy=$('#copy-summary-button'),cf=$('#copy-feedback'),top=$('#back-to-top');fs?.addEventListener('click',async()=>{try{if(!document.fullscreenElement){await document.documentElement.requestFullscreen();fs.textContent='Salir de pantalla completa';toast('Modo pantalla completa activado.')}else{await document.exitFullscreen();fs.textContent='Pantalla completa';toast('Pantalla completa desactivada.')}}catch(e){toast('El navegador no permite pantalla completa en este contexto.')}});pr?.addEventListener('click',()=>print());copy?.addEventListener('click',async()=>{const s='Identificar riesgos y protección, formular objetivos breves, activar apoyos realistas, coordinar sistemas y revisar resultados con indicadores observables.';try{await navigator.clipboard.writeText(s);if(cf)cf.textContent='Síntesis copiada al portapapeles.';toast('Texto copiado.')}catch(e){if(cf)cf.textContent='No se pudo copiar automáticamente. Selecciona el texto y cópialo manualmente.'}});top?.addEventListener('click',()=>scrollTo({top:0,behavior:prm?'auto':'smooth'}))}
function anchors(){$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const t=$(a.getAttribute('href'));if(!t||prm)return;e.preventDefault();t.scrollIntoView({behavior:'smooth',block:'start'});history.pushState(null,'',a.getAttribute('href'))}))}
function boot(){reading();menu();reveal();spy();caseExplorer();toolLab();routeLab();checklist();utils();anchors();progress();addEventListener('scroll',progress,{passive:true});addEventListener('resize',progress)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();
